### ISSUE TITLE
SparkFun Qwiic Button -

### ISSUE THREAD

**Issue by gigapod** [sparkfun/pdp-qwiic-micro-python#10]
### Board

[SparkFun Qwiic Button - Green LED](https://www.sparkfun.com/products/16842)

### Notes

* Existing [Driver](https://github.com/sparkfun/Qwiic_Button_Py)

**Comment by faludi** [comment]
I'd been using an older version of qwiic_i2c on our production devices. Updating now to the latest version and noticed an exception being thrown by a few of the more basic LED functions in the Qwiic_Button module. It will accept LED_config but has issues with LED_on and LED_off. Hopefully you can reproduce, here's what I'm seeing:

```
MicroPython v1.20.0-1841-g2c5ca5f58 on 2023-11-27; XBC Global LTE-M/NB-IoT with EFR32MG
Type "help()" for more information.
>>> import qwiic_button
>>> bt=qwiic_button.QwiicButton()
>>> bt.LED_config(12, 3000, 500)
>>> bt.LED_on(255)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/flash/lib/qwiic_button.py", line 722, in LED_on
  File "/flash/lib/qwiic_button.py", line 689, in LED_config
  File "/flash/lib/qwiic_i2c/micropython_i2c.py", line 146, in writeWord
OSError: [Errno 7019] ENODEV
```

The older version of qwiic_i2c does this just fine so hopefully it's a simple fix. Thanks!

**Comment by sfe-SparkFro** [comment]
Hi Rob, apologies for the long delay here! I've been very busy with some other projects and am working through my backlog.

I am able to replicate the ENODEV error message you're seeing. However when I connect an oscilloscope, it appears the problem is with the Qwiic Button not sending the ACK bit correctly sometimes, which should have nothing to do with the I2C driver:

![image](https://github.com/sparkfun/pdp-qwiic-micro-python/assets/102242586/4405a861-28c5-41a3-8af5-dd39ac69e5dd)

The behavior is also quite strange. If I call `LED_config()` once, it usually fails to ACK. But if I call it again, then it typically works. Though the second call typically has some clock stretching, and no more clock stretching on subsequent calls.

![image](https://github.com/sparkfun/pdp-qwiic-micro-python/assets/102242586/8a7b3fad-a18a-4a0d-819d-50fb66e9a2ac)

The same things happens when I call `LED_on()`. If I switch back and forth between those 2 calls, it fails to ACK most (but not all) of the time. Strange...

Looking closer, here's what some good ACKs look like:

![image](https://github.com/sparkfun/pdp-qwiic-micro-python/assets/102242586/275e013d-f959-43b1-924b-568cacc4fa34)

And here's one of the failed ACKs:

![image](https://github.com/sparkfun/pdp-qwiic-micro-python/assets/102242586/976a7c8d-af6e-410b-b4c0-024b276eea41)

It does actually bring the SDA line low, but _just barely after_ the SCL line goes low. I'm guessing the ATtiny driving the Qwiic Button just isn't pulling that pin low fast enough for some reason.

However that begs the question, why does it seem to work fine when you switch to an older I2C driver? Do you know exactly which version you're using? Or perhaps you can just send a copy of the files you're using so I can try to replicate and debug on my end?

Thanks!

**Comment by faludi** [comment]
Hi Dryw,

Here’s the older driver files that appear to work with the button and keypad. It’s been a good while since I last dealt with this so let me know if you don’t get positive results and I can set up another test on my end.

￼

Cheers,
—Rob

**Comment by faludi** [comment]
Hi Dryw,

Here’s the older driver files that appear to work with the button and keypad. It’s been a good while since I last dealt with this so let me know if you don’t get positive results and I can set up another test on my end.

Cheers!
[qwiic_i2c.zip](https://github.com/user-attachments/files/15979614/qwiic_i2c.zip)

**Comment by sfe-SparkFro** [comment]
Thanks Rob!

I just replaced my I2C files with those, and am still seeing the ENODEV error as described above. 

If you have time, could you please try running the following code and let me know what happens?

```
import time
import qwiic_button

bt=qwiic_button.QwiicButton()

for i in range(10):
    print(i)
	
    try:
		bt.LED_config(12, 3000, 500)
		print("LED_config PASS")
	except:
		print("LED_config FAIL")
    
	time.sleep(1)
    
	try:
		bt.LED_on(255)
		print("LED_on PASS")
	except:
		print("LED_on FAIL")
    
	time.sleep(1)

for i in range(10):
    print(i)
	
    try:
		bt.LED_config(12, 3000, 500)
		print("LED_config PASS")
	except:
		print("LED_config FAIL")
    
	time.sleep(1)

for i in range(10):
    print(i)
    
	try:
		bt.LED_on(255)
		print("LED_on PASS")
	except:
		print("LED_on FAIL")
    
	time.sleep(1)
```

For reference, this is what it's printing on my end:

```
0
LED_config FAIL
LED_on PASS
1
LED_config FAIL
LED_on FAIL
2
LED_config FAIL
LED_on FAIL
3
LED_config PASS
LED_on FAIL
4
LED_config FAIL
LED_on FAIL
5
LED_config FAIL
LED_on FAIL
6
LED_config PASS
LED_on FAIL
7
LED_config FAIL
LED_on PASS
8
LED_config FAIL
LED_on PASS
9
LED_config FAIL
LED_on FAIL
0
LED_config FAIL
1
LED_config PASS
2
LED_config PASS
3
LED_config PASS
4
LED_config PASS
5
LED_config PASS
6
LED_config PASS
7
LED_config PASS
8
LED_config PASS
9
LED_config PASS
0
LED_on FAIL
1
LED_on PASS
2
LED_on PASS
3
LED_on PASS
4
LED_on PASS
5
LED_on PASS
6
LED_on PASS
7
LED_on PASS
8
LED_on FAIL
9
LED_on PASS
```

When alternating function calls, it usually fails. When performing the same function call sequentially, it usually passes. I believe all the fails are just caused by the ACK bit being sent too late, so I suspect that's the root problem, and not the driver version. That also means that I suspect your success with the older driver is just coincidental, but I want to run this test to verify that we have the same behavior. If we get different behavior, then I'll be very confused 😉

**Comment by faludi** [comment]
Hmm, well unfortunately we're not seeing the same results. Here's my capture, from a Digi XBee 3 Global LTE-M/NB-IoT. The first session in the log uses the OLDER library in the zip file that I posted above. (I re-downloaded and unzipped that particular file just to make sure.) The second session uses a fresh download of the NEW qwiic_i2c library that's up on GitHub. Second session has a mix of PASS and FAIL very similar what you posted above. First session using the zip file posted here only shows PASS messages. Maybe the older library only runs properly East of the Mississippi? It's gotta be _something_...

[CoolTerm Capture (Untitled_0) 2024-06-26 13-55-46-297.txt](https://github.com/user-attachments/files/15993559/CoolTerm.Capture.Untitled_0.2024-06-26.13-55-46-297.txt)

**Comment by sfe-SparkFro** [comment]
Darn, different results between us will make debugging harder! Not sure what would be causing the different behavior. When I have a moment, I will try to do a completely fresh install of everything, test, swap the I2C driver, and test again; maybe I have some other software that's outdated or something?

In the meantime, do you have an oscilloscope that you can connect to probe the I2C lines, both in the PASS and FAIL conditions? I'm very curious to know what's going on electrically on your side, and whether there's an obvious difference there.

Thanks!

**Comment by faludi** [comment]
Hmm, I only have a pretty basic meter here, not a full scope.

My setup uses just the code you sent as my main.py, and the qwiic_button.py module then swapping between the two qwiic_i2c modules. The XBee is running the latest firmware, though this was happening earlier on previous XBee firmware as well. Hardware is the XBee mentioned above, the SFE XBee Development Board, a qwiic cable and the qwiic button itself. Power is from USB-C so that should be pretty clean.

This isn't a big issue on our end, however it would be great to figure it out before it jams up some other user. Let me know what you find out with your test and we can take it from there.

**Comment by sfe-SparkFro** [comment]
Ok, even more bizarre now. I basically wiped the file system of my XBee, re-uploaded the [Qwiic Button driver](https://github.com/sparkfun/Qwiic_Button_Py/blob/main/qwiic_button.py) and the latest [Qwiic_I2C_Py driver](https://github.com/sparkfun/Qwiic_I2C_Py/tree/master/qwiic_i2c), and now it's working totally fine:

```
0
LED_config PASS
LED_on PASS
1
LED_config PASS
LED_on PASS
2
LED_config PASS
LED_on PASS
3
LED_config PASS
LED_on PASS
4
LED_config PASS
LED_on PASS
5
LED_config PASS
LED_on PASS
6
LED_config PASS
LED_on PASS
7
LED_config PASS
LED_on PASS
8
LED_config PASS
LED_on PASS
9
LED_config PASS
LED_on PASS
```

Oh, do I love inconsistent issues!

It's possible the issue is related to the [Qwiic Button driver](https://github.com/sparkfun/Qwiic_Button_Py/blob/main/qwiic_button.py), could you please install the latest version and see if that makes a difference? Perhaps you've got an older version installed?

For reference, I'm also using a [Digi XBee 3 Global LTE-M/NB-IoT](https://www.sparkfun.com/products/22329), with firmware version 1161E according to XCTU.

**Comment by faludi** [comment]
Well I did have a (slightly) older version of the Qwiic Button Driver, but unfortunately after installing the newest one I have the same results. The older Qwiic I2C Py driver gives me PASS messages on everything and the newest Qwiic I2C Py driver presents a mix of PASS and FAIL. So I factory reset my XBee, reformatted the file system and tried again with everything clean. Same results.

I’m sure I have the newest version of the drivers because I used your links above to re-download both the latest Button and I2C ones directly from GitHub. Not sure where we go from here. I guess you should re-confirm that you're really using the newest I2C driver, that's the only thing I can think of--some kind of slip-up where you installed the old one instead of the new. Seems unlikely but given our different results might be worth a quick try. We're definitely using the same XBee, with the same firmware version. Weird!

[CoolTerm Capture (Untitled_0) 2024-06-28 10-49-57-303.txt](https://github.com/user-attachments/files/16032374/CoolTerm.Capture.Untitled_0.2024-06-28.10-49-57-303.txt)

**Comment by sfe-SparkFro** [comment]
Ok, now it's even weirder. I ran the exact same test as yesterday without changing anything, and now it's failing on me. I'm gonna rip my hair out...

I will play around with this some more to see if I can debug what's going on, and hopefully find a solution. Can't guarantee if or when that will be, but hopefully I can soon!

**Comment by faludi** [comment]
No! Leave the hair alone, it's your brand!

**Comment by sfe-SparkFro** [comment]
😄

Also, I did just discover one silly thing I was doing - I was pressing Ctrl+B in an effort to perform a soft reset, but the correct keypress for that is Ctrl-D... I think that's why it was working yesterday; I had initially loaded the old I2C driver followed by the latest one, and it still had the old driver in memory since I didn't actually reset it properly. Now it's failing with the new driver, and passing with the old one.

**Comment by faludi** [comment]
Aha! Yes, that would explain it. Ctrl+B simply shows the banner but has no other effect. Phew, well at least we have the same results now. And actually that's awesome, mystery solved!

Here's the official documentation on keyboard commands for the XBee REPL: https://www.digi.com/resources/documentation/digidocs/90002219/Default.htm#reference/r_shortcuts.htm?TocPath=Keyboard%2520shortcuts%257C_____1 

(Ctrl+E, Ctrl+F and Ctrl+R were implemented because initially, the XBee didn't have a file system, so they allowed pasting, saving and run of code. Now with a real file system, these go mostly unused but they still work and are occasionally useful.)

**Comment by sfe-SparkFro** [comment]
Thanks for that!

I have made a discovery - the old I2C driver defaults to 400kHz (originally chosen for speed), whereas the new driver defaults to 100kHz (changed for better compatibility).

The ATtiny running the Qwiic Button is relatively slow and can't really keep up with I2C even at 100kHz, so it really needs to perform clock stretching. At 400kHz, it appears to do clock stretching all the time:

![image](https://github.com/sparkfun/pdp-qwiic-micro-python/assets/102242586/ad6d035d-d6ae-4c15-9c70-41f4deb10b91)

At 100kHz, it also appears to do clock stretching, but not always, sometimes resulting in a delayed ACK and an ENODEV error (see 2.0ms vs 2.3ms in this trace):

![image](https://github.com/sparkfun/pdp-qwiic-micro-python/assets/102242586/2c91ed29-19fe-4912-85af-0611dff96431)

No idea why it sometimes fails to clock stretch at 100kHz, but that seems to be the root problem. I might try playing around with this on other platforms to see whether this problem is exclusive to the XBee (somehow?). But if you want to use the latest I2C driver, you should be able to workaround this by setting the clock to 400kHz.

**Comment by sfe-SparkFro** [comment]
Huh, seems like this problem is exclusive to the XBee.

I tested with an [XRP](https://www.sparkfun.com/products/22230) running MicroPython and the latest I2C driver and Qwiic Button driver, and it worked flawlessly with no failed ACKs. I also tested with an [ESP32 Thing Plus](https://www.sparkfun.com/products/20168) with our [Arduino library](https://github.com/sparkfun/SparkFun_Qwiic_Button_Arduino_Library) (basically the same `LED_config()` and `LED_on()` code), which also had no issues.

I'm not sure what to make of that. According to my scope, the problem appears to be that the Qwiic Button is failing to clock stretch for its ACK sometimes, but I don't understand how the XBee could possibly cause that to happen. I don't know where to go with this.

**Comment by sfe-SparkFro** [comment]
I picked a couple brains around the office, the consensus is a lot of head scratching.

If you want to use the latest I2C driver, my suggestion for now would be to just set the clock frequency to 400kHz. This passes every time on my end with the latest I2C driver:

```
import time
import qwiic_button
import qwiic_i2c

bus = qwiic_i2c.get_i2c_driver(freq=400000)

bt=qwiic_button.QwiicButton(i2c_driver = bus)

for i in range(10):
    print(i)
	
    try:
		bt.LED_config(12, 3000, 500)
		print("LED_config PASS")
	except:
		print("LED_config FAIL")
    
	time.sleep(1)
    
	try:
		bt.LED_on(255)
		print("LED_on PASS")
	except:
		print("LED_on FAIL")
    
	time.sleep(1)
```

Perhaps Digi can take a closer look at this? Since it works fine on other platforms, that must indicated the XBee is doing _something_ differently. That's not to say the difference in behavior on the XBee is _wrong_, just different.

**Comment by faludi** [comment]
The XBee implements the SiLabs i2c feature set, so I'm not sure how much Digi engineers even have access to. Rather than go down the rabbit hole of figuring it out, maybe I'll stick to this excellent workaround since it's just a small code change. Will try implementing this for the button and later the keypad and I'll tell you how it goes.

**Comment by sfe-SparkFro** [comment]
Fair enough! We have seen issues like this before (likely the same issue) with other platforms and Qwiic products using the ATtiny, so it would be nice to get to the bottom of it at some point. But that's probably a task for another day.

**Comment by faludi** [comment]
Looking good on both button and keypad. I still see a _very_ occasional ENODEV but since my calls are wrapped in a try-except block this does not create any problem for the application. I agree it would be interesting to look at further, will mention it to the devs next time we chat. Thanks much!
