### ISSUE TITLE
SparkFun Ambient Light Sensor - VEML6030

### ISSUE THREAD

**Issue by gigapod** [sparkfun/pdp-qwiic-micro-python#6]
### Board

[SparkFun Ambient Light Sensor - VEML6030](https://www.sparkfun.com/products/15436)

### Notes
[Driver](https://github.com/sparkfun/Qwiic_VEML6030_Py)
* XBee - originally wanted the  VEML7700, but that's an SparkX board

**Comment by malcolm-sparkfun** [comment]
@sfe-SparkFro 

1) Can mention [here](https://github.com/sparkfun/Qwiic_VEML6030_Py/blob/master/qwiic_veml6030.py#L273) that we can also return an error. This goes for all the functions in this file that can return an error. 
2) Should [this line](https://github.com/sparkfun/Qwiic_VEML6030_Py/blob/master/qwiic_veml6030.py#L491) be reads/gets the low threshold rather than sets? Same thing is [here](https://github.com/sparkfun/Qwiic_VEML6030_Py/blob/master/qwiic_veml6030.py#L518)

**Comment by sfe-SparkFro** [comment]
Good catches! Since they're just a couple minor things in the comments, they're not a big deal. If you'd like to fix them, go for it, but also fine if you'd prefer to leave it!
